name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing this bug report!
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
      placeholder: Fill this out!
      value: "Help!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Paste any relevant log outputs here.
      render: shell
