name: gh-actions
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - flake8
  - mamba
  - sphinx
  - ca-certificates
  - certifi
  - openssl
  - sphinx_rtd_theme
  - autoflake
  - blackdoc
  - pre-commit
  - pytest
  - pytest-cov
