name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test
      - name: download artifact?
        uses: actions/download-artifact@v2
        with:
          name: test-log-file
      - run: npm install -g bats
      - run: bats -v
