name: learn-github-actions
on:
  push:
    branches:
      - 'main'
jobs:
  miniconda:
    name: Miniconda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pysample-test
          environment-file: ci/environment.yml
          python-version: '3.10'
          channels: conda-forge
          auto-activate-base: false
      - name: Install pysample
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov --cov-report=xml --cov-report=html
